version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mkcdbpass
      - POSTGRES_DB=mkcdb
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      - db
    volumes:
      - ./logs:/mkc-backend/logs
      - ../storage/:/mkc-backend/storage
  backup:
    build:
      context: .
      dockerfile: ./cmd/db-backup/Dockerfile
    volumes:
      - ./backups:/backups
    depends_on:
      - db
  notecheker:
    build:
      context: .
      dockerfile: ./cmd/notechecker/Dockerfile
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db


volumes:
  db:
    driver: local