basePath: /
host: localhost:8080
info:
  contact:
    email: mail-bla-bla
  description: MK CLOUD backend service.
  title: MKC API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
