basePath: /
definitions:
  app.AuthToken:
    properties:
      token:
        type: string
    type: object
  app.errorResponse:
    properties:
      message:
        type: string
    type: object
  app.successResponse:
    properties:
      message:
        type: string
    type: object
  ds.AddParticipantReq:
    type: object
  ds.CreateProjectReq:
    properties:
      name:
        type: string
    type: object
  ds.Customer:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      login:
        type: string
      password:
        type: string
      second_name:
        type: string
      type:
        type: integer
    type: object
  ds.DeleteParticipantReq:
    type: object
  ds.DeleteProjectReq:
    type: object
  ds.LoginCustomerReq:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  ds.Project:
    properties:
      admin_id:
        type: string
      capacity:
        type: integer
      creation_date:
        type: string
      id:
        type: string
      name:
        type: string
      owner_id:
        type: string
    type: object
  ds.SignUpCustomerReq:
    properties:
      email:
        type: string
      first_name:
        type: string
      login:
        type: string
      password:
        type: string
      second_name:
        type: string
    type: object
  ds.UpdateProjectNameReq:
    type: object
host: localhost:8080
info:
  contact:
    email: mail@dump
  description: MK CLOUD backend service.
  title: MKC API
  version: "1.0"
paths:
  /admin/project:
    post:
      description: Attachs admin to project
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Project'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      security:
      - BearerAuth: []
      summary: Attachs admin to project
      tags:
      - auth
  /login:
    post:
      description: Login customer
      parameters:
      - description: Customer data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/ds.LoginCustomerReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.AuthToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      summary: Login customer
      tags:
      - auth
  /logout:
    get:
      description: Logout user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.successResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/app.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - auth
  /participants/{project_id}:
    delete:
      description: Removes participant from project
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: string
      - description: CHANGE IT
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/ds.DeleteParticipantReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Customer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      security:
      - BearerAuth: []
      summary: Removes participant from project
      tags:
      - auth
    post:
      description: Adds participant to project
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: string
      - description: CHANGE IT
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/ds.AddParticipantReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Customer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      security:
      - BearerAuth: []
      summary: Adds participant to project
      tags:
      - auth
  /project:
    post:
      description: Creates customer project in storage
      parameters:
      - description: New project
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/ds.CreateProjectReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Project'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      security:
      - BearerAuth: []
      summary: Creates customer project
      tags:
      - project
  /project/{project_id}:
    delete:
      description: Deletes project
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: string
      - description: CHANGE IT
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/ds.DeleteProjectReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Customer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      security:
      - BearerAuth: []
      summary: Deletes project
      tags:
      - auth
    put:
      description: Updates project name
      parameters:
      - description: Project ID
        in: path
        name: project_id
        required: true
        type: string
      - description: New project name
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/ds.UpdateProjectNameReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Project'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      security:
      - BearerAuth: []
      summary: Updates project name
      tags:
      - auth
  /signup:
    post:
      description: Signup customer
      parameters:
      - description: Customer data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/ds.SignUpCustomerReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.AuthToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.errorResponse'
      summary: Signup customer
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
